[project]
name = "expense-tracker-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ratura Practice", email = "ratura@example.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=4.0.7",
    "libsql-client>=0.3.1",
]

[project.scripts]
expense-tracker-mcp = "expense_tracker_mcp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
